// Autogenerated, do not edit.

'use strict';

const data = require('./genesis-data.json');
const genesis = exports;

/*
 * Main
 */

genesis.main = {
  version: 0,
  hash: Buffer.from(
    '190baed298cdd7d9275e4fb96d14a905ac76a52b49e7685511e35675258fd429',
    'hex'),
  prevBlock: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  merkleRoot: Buffer.from(
    '1da0028b82ca41f1d3535cab17eb9f0853ba7b6d7fa73e4c9cb9f4d68a13fe3f',
    'hex'),
  witnessRoot: Buffer.from(
    '5e20903103514e01d9707cddad0a31f3fa677daaf664c7bed9591d5c5e854b98',
    'hex'),
  treeRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  filterRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  reservedRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  time: 1548148523,
  bits: 0x1d00ffff,
  nonce: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  height: 0
};

genesis.mainData = Buffer.from(data.main, 'base64');

/*
 * Testnet
 */

genesis.testnet = {
  version: 0,
  hash: Buffer.from(
    '9b7a885b9fab5c152f8cbfc048b2838217dc129f75162ab704fe38792e465b00',
    'hex'),
  prevBlock: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  merkleRoot: Buffer.from(
    '1da0028b82ca41f1d3535cab17eb9f0853ba7b6d7fa73e4c9cb9f4d68a13fe3f',
    'hex'),
  witnessRoot: Buffer.from(
    '5e20903103514e01d9707cddad0a31f3fa677daaf664c7bed9591d5c5e854b98',
    'hex'),
  treeRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  filterRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  reservedRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  time: 1548148524,
  bits: 0x1d300000,
  nonce: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  height: 0
};

genesis.testnetData = Buffer.from(data.testnet, 'base64');

/*
 * Regtest
 */

genesis.regtest = {
  version: 0,
  hash: Buffer.from(
    'ca153b688eac1c21084a3e8e30f59bd4e4ab3398928915e3b2b37ed826521cfe',
    'hex'),
  prevBlock: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  merkleRoot: Buffer.from(
    '1da0028b82ca41f1d3535cab17eb9f0853ba7b6d7fa73e4c9cb9f4d68a13fe3f',
    'hex'),
  witnessRoot: Buffer.from(
    '5e20903103514e01d9707cddad0a31f3fa677daaf664c7bed9591d5c5e854b98',
    'hex'),
  treeRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  filterRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  reservedRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  time: 1548148525,
  bits: 0x207fffff,
  nonce: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  height: 0
};

genesis.regtestData = Buffer.from(data.regtest, 'base64');

/*
 * Simnet
 */

genesis.simnet = {
  version: 0,
  hash: Buffer.from(
    '9ecde16298fad80ab87e34da3d853319fb2391b9c780245e048d6e5c95cbd473',
    'hex'),
  prevBlock: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  merkleRoot: Buffer.from(
    '1da0028b82ca41f1d3535cab17eb9f0853ba7b6d7fa73e4c9cb9f4d68a13fe3f',
    'hex'),
  witnessRoot: Buffer.from(
    '5e20903103514e01d9707cddad0a31f3fa677daaf664c7bed9591d5c5e854b98',
    'hex'),
  treeRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  filterRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  reservedRoot: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  time: 1548148526,
  bits: 0x207fffff,
  nonce: Buffer.from(
    '0000000000000000000000000000000000000000000000000000000000000000',
    'hex'),
  height: 0
};

genesis.simnetData = Buffer.from(data.simnet, 'base64');
