name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:

    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1

    - name: Install
      run: sudo apt-get install -y libunbound-dev |
           npm install nyc coveralls bslint

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test-ci

    - name: Coverage
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
