name: Node.js

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  general-build:
    name: Lint and Test Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: sudo apt-get install -y libunbound-dev |
           npm install nyc coveralls bslint @hns-dev/bsdoc

    - name: Lint
      run: npm run lint

    - name: Build Docs
      run: npm run build-docs

    - name: Test
      run: npm run test-ci

    - name: Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node: [12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Update npm
      run: npm i -g npm

    - name: Install libunbound
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get install -y libunbound-dev

    - name: Install
      run: npm install

    - name: Test
      run: npm run test

  build-windows:
    name: Build windows & node.js v18
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Update npm
      run: npm i -g npm

    - name: Install
      run: npm install

    - name: Test
      run: npm run test
