name: Tweet on Release

on:
  release:
    types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Send tweet
        if: >-
          ${{ secrets.TWITTER_CONSUMER_KEY != '' &&
              secrets.TWITTER_CONSUMER_SECRET != '' &&
              secrets.TWITTER_ACCESS_TOKEN != '' &&
              secrets.TWITTER_ACCESS_TOKEN_SECRET != '' }}
        run: node scripts/tweet-release.js
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
